### ISSUE TITLE
Catch error if first machine is not 0

### ISSUE THREAD

**Issue by tvanhove** [galgalesh/tengu-charms#13]
> Traceback (most recent call last):
>   File "/opt/tengu/scripts/tengu.py", line 486, in <module>
>     g_cli()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/opt/tengu/scripts/tengu.py", line 250, in c_create
>     provider_env = PROVIDER.create_from_bundle(env_conf, bundledict)
>   File "/opt/tengu/scripts/jfed_provider/provider.py", line 30, in create_from_bundle
>     env.generate_rspec(bundle)
>   File "/opt/tengu/scripts/jfed_provider/provider.py", line 109, in generate_rspec
>     data = get_data_from_bundle(bundle)
>   File "/opt/tengu/scripts/jfed_provider/provider.py", line 135, in get_data_from_bundle
>     if not machines.get(str(m_id)): raise Exception('machine {} not found while number of machines is {}.'.format(m_id, len(machines)))
> Exception: machine 0 not found while number of machines is 3

Caused by invalid YAML file below:

> machines:
>  '1':
>     constraints: 'arch=amd64 testbed=wall1 pubipv4==true'
>     series: trusty
>   '2':
>     constraints: 'arch=amd64 testbed=wall1'
>     series: trusty
>   '3':
>     constraints: 'arch=amd64 testbed=wall1'
>     series: trusty
> 

Above error should be caught cleanly instead of printing stacktrace

**Comment by galgalesh** [comment]
Fixed https://github.com/galgalesh/tengu-charms/commit/a7a9d95cb0a20b67e421b2a35dc2b6564b577747
