### ISSUE TITLE
Catch error if YAML contains language erros

### ISSUE THREAD

**Issue by tvanhove** [galgalesh/tengu-charms#14]
> Traceback (most recent call last):
>   File "/opt/tengu/scripts/tengu.py", line 486, in <module>
>     g_cli()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/opt/tengu/scripts/tengu.py", line 248, in c_create
>     bundledict = yaml.load(bundle_file)
>   File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
>     return loader.get_single_data()
>   File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
>     node = self.get_single_node()
>   File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
>     document = self.compose_document()
>   File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
>     node = self.compose_node(None, None)
>   File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
>     node = self.compose_mapping_node(anchor)
>   File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
>     item_value = self.compose_node(node, item_key)
>   File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
>     node = self.compose_sequence_node(anchor)
>   File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
>     while not self.check_event(SequenceEndEvent):
>   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
>     self.current_event = self.state()
>   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 384, in parse_block_sequence_entry
>     if not self.check_token(BlockEntryToken, BlockEndToken):
>   File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
>     self.fetch_more_tokens()
>   File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 252, in fetch_more_tokens
>     return self.fetch_plain()
>   File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 676, in fetch_plain
>     self.tokens.append(self.scan_plain())
>   File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 1305, in scan_plain
>     "Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.")
> yaml.scanner.ScannerError: while scanning a plain scalar
>   in "bundle.yaml", line 49, column 6
> found unexpected ':'
>   in "bundle.yaml", line 49, column 12
> Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.

Above error should be clearly caught as it indicates error agains YAML notation

Was caused in this case by relations in Juju bundle:

> relations:
>   - [nimbus:master, sworker:worker]

Requires quotes around relation names because of colon:

> relations:
>   - ["nimbus:master", "sworker:worker"]

**Comment by galgalesh** [comment]
Fixed: https://github.com/galgalesh/tengu-charms/commit/193652d16dae93c5a8935a4b4d7a3467c09efbe0
